### ISSUE TITLE
README doesn't fit to the actual implementation

### ISSUE THREAD

**Issue by stlankes** [gz/rust-multiboot#9]
If I see it correctly, a new trait is introduced and must be used to initialize `Multiboot` (see also `Multiboot::from_ptr`). The readme doesn't explained it. Or do I miss something?

**Comment by gz** [comment]
Ah you're right, I'll need to update the readme that is outdated after we merged @YtvwlD pull requests.

It is semi-documented by having some example code in the tests at the moment: https://github.com/gz/rust-multiboot/blob/master/tests/read_information.rs#L27

**Comment by YtvwlD** [comment]
Oh yes, sorry. I totally missed the README.

(There is also documentation about the [trait](https://docs.rs/multiboot/0.6.0/multiboot/information/trait.MemoryManagement.html) and the [`from_ptr` method](https://docs.rs/multiboot/0.6.0/multiboot/information/struct.Multiboot.html#method.from_ptr).)

**Comment by stlankes** [comment]
I was able to understand the test cases. :-)

**Comment by paulcacheux** [comment]
Hi, the readme is still not coherent with the actual code. The documentation link on the crates.io page is also not the current version (it seems to be documenting the 0.3 version). Would you be open to some pull requests trying to fix that ?

**Comment by gz** [comment]
@paulcacheux absolutely, feel free to send a pull request to improve the doc/readme I'm happy to merge/release a new version

**Comment by gz** [comment]
Fixed in #10, thanks!
